#! /usr/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width        4
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

${HOME}/.config/polybar/launch.sh

# For bspwm overriding, adjust this value manually
bspc config top_padding 33
bspc config bottom_padding 33

bspc config focused_border_color "#9D0006"

feh --bg-scale --no-fehbg ${HOME}/Pictures/wallpaper.jpg

emacs --daemon &
